services:
  db:
    image: mariadb:11
    container_name: plotgram-db-dev
    environment:
      MARIADB_DATABASE: plotgram
      MARIADB_USER: plotgram
      MARIADB_PASSWORD: plotgram
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data_dev:/var/lib/mysql
    networks:
      - tfgnet

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/plotgram
      SPRING_DATASOURCE_USERNAME: plotgram
      SPRING_DATASOURCE_PASSWORD: plotgram
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      TMDB_TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIyMzUwYmI3MjE4NDYwZGNiNjM0ZmZmYWM1YjdlMDI5YSIsIm5iZiI6MTc1MjA4MTMyNC42MjksInN1YiI6IjY4NmVhM2FjMWI5YThhYjFlOGE5NjYwOSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.K0r9kC62EHEhKtiPgpT32bsah8K_zbeaxiLAhTYSu9s
      TMDB_BASE_URL: https://api.themoviedb.org/3
      TMDB_LANG: es-ES
    networks:
      - tfgnet

  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - tfgnet

volumes:
  mariadb_data_dev:

networks:
  tfgnet:
