services:
  db:
    image: mariadb:11
    container_name: plotgram-db
    environment:
      MARIADB_DATABASE: plotgram
      MARIADB_USER: plotgram
      MARIADB_PASSWORD: plotgram
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - tfgnet

  backend:
    build:
      context: ./backend
    container_name: tfg-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    environment:
        SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
        SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
        SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
        SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
        TMDB_TOKEN: ${TMDB_TOKEN}
        GEMINI_API_KEY: ${GEMINI_API_KEY}
        JWT_SECRET: ${JWT_SECRET}
        ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    networks:
      - tfgnet

  frontend:
    build:
      context: ./frontend
    container_name: tfg-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - tfgnet

volumes:
  mariadb_data:

networks:
  tfgnet:
