services:
  db:
    image: mariadb:11
    container_name: plotgram-db
    environment:
      MARIADB_DATABASE: plotgram
      MARIADB_USER: plotgram
      MARIADB_PASSWORD: plotgram
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - tfgnet

  backend:
    build:
      context: ./backend
    container_name: tfg-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
        SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/plotgram
        SPRING_DATASOURCE_USERNAME: plotgram
        SPRING_DATASOURCE_PASSWORD: plotgram
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
        TMDB_TOKEN: ${TMDB_TOKEN}
        TMDB_BASE_URL: ${TMDB_BASE_URL}
        TMDB_LANG: ${TMDB_LANG}
    networks:
      - tfgnet

  frontend:
    build:
      context: ./frontend
    container_name: tfg-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - tfgnet

volumes:
  mariadb_data:

networks:
  tfgnet:
