server:
  port: 8080

spring:
  application:
    name:backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3307/plotgram}
    username: ${SPRING_DATASOURCE_USERNAME:plotgram}
    password: ${SPRING_DATASOURCE_PASSWORD:plotgram}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    open-in-view: false
    show-sql: false

tiempoExpiracionTokenJwtMin: 40

tmdb:
  base-url: https://api.themoviedb.org/3
  token: ${TMDB_TOKEN}
  lang: es-ES
gemini:
  api-key: ${GEMINI_API_KEY}
  model: gemini-2.5-flash
plotgram:
  admin:
    nombre: ${ADMIN_NAME:admin}
    password: ${ADMIN_PASSWORD}
    email: ${ADMIN_EMAIL:admin@email.com}

app:
  auth:
    jwt:
      secret: ${JWT_SECRET}
      clockSkewSeconds: 30
      refrescarventana: 10
      maxhorassesion: 8
    cookie:
      secure=false
      samesite=Lax